import test from 'node:test'
import assert from 'node:assert/strict'
import { join } from 'node:path'

import { REPO_ROOT, readText } from './helpers/test-env.mjs'

test('workflow runtime contract keeps route and state scripts aligned', () => {
  const notifyContext = readText(join(REPO_ROOT, 'scripts', 'notify-context.mjs'))
  assert.match(notifyContext, /请根据用户请求的真实意图选路/)
  assert.match(notifyContext, /不依赖关键词表/)
  assert.match(notifyContext, /只读探索/)
  assert.match(notifyContext, /默认先走 ~plan \/ ~prd/)
  assert.match(notifyContext, /当前活跃 plan \/ PRD/)
  assert.match(notifyContext, /describeProjectStoreFile/)
  assert.match(notifyContext, /项目状态：/)
  assert.match(notifyContext, /当前按需能力|buildCapabilityHint|capabilityHint/)
  assert.match(notifyContext, /buildProjectStorageBlock/)
  assert.match(notifyContext, /先看当前用户消息确认仍是同一任务/)
  assert.match(notifyContext, /恢复快照/)

  const projectStorage = readText(join(REPO_ROOT, 'scripts', 'project-storage.mjs'))
  assert.match(projectStorage, /project_store_mode/)
  assert.match(projectStorage, /repo-shared/)
  assert.match(projectStorage, /当前项目存储/)
  assert.match(projectStorage, /knowledge_base_dir/)

  const guard = readText(join(REPO_ROOT, 'scripts', 'guard.mjs'))
  assert.match(guard, /高风险链路提醒/)
  assert.match(guard, /Blocked T3 command until workflow reaches VERIFY \/ CONSOLIDATE/)
  assert.match(guard, /still requires ~plan before risky schema changes/)
  assert.match(guard, /buildStateSyncHint/)
  assert.match(guard, /buildIdeaBoundaryReason/)
  assert.match(guard, /当前路由：~idea 是只读探索/)

  const guardRules = readText(join(REPO_ROOT, 'scripts', 'guard-rules.mjs'))
  assert.match(guardRules, /HIGH_RISK_COMMAND_PATTERNS/)
  assert.match(guardRules, /IDEA_SIDE_EFFECT_COMMAND_PATTERNS/)
  assert.match(guardRules, /Package publish command/)

  const notifyRoute = readText(join(REPO_ROOT, 'scripts', 'notify-route.mjs'))
  assert.doesNotMatch(notifyRoute, /pending_action_prompted/)
  assert.doesNotMatch(notifyRoute, /pending-action-state/)

  const deliveryGate = readText(join(REPO_ROOT, 'scripts', 'delivery-gate.mjs'))
  assert.match(deliveryGate, /workflow-aware completion gate/)
  assert.match(deliveryGate, /missing required artifacts/)
  assert.match(deliveryGate, /template placeholders/)
  assert.match(deliveryGate, /under-specified task metadata/)
  assert.match(deliveryGate, /missing a trustworthy structured contract/)
  assert.match(deliveryGate, /missing acceptance/)
  assert.match(deliveryGate, /missing validation/)
  assert.match(deliveryGate, /missing fresh verification evidence/)
  assert.match(deliveryGate, /missing fresh advisor evidence/)
  assert.match(deliveryGate, /missing fresh visual validation evidence/)
  assert.match(deliveryGate, /missing fresh closeout evidence/)
  assert.match(deliveryGate, /\.helloagents\/\.ralph-visual\.json/)
  assert.match(deliveryGate, /\.helloagents\/\.ralph-closeout\.json/)
  assert.match(deliveryGate, /Recommended path:/)
  assert.match(deliveryGate, /buildDeliveryGateHint/)
  assert.match(deliveryGate, /getVerifyEvidenceStatus/)
  assert.match(deliveryGate, /getReviewEvidenceStatus/)

  const verifyState = readText(join(REPO_ROOT, 'scripts', 'verify-state.mjs'))
  assert.match(verifyState, /VERIFY_EVIDENCE_FILE_NAME/)
  assert.match(verifyState, /\.ralph-verify\.json/)
  assert.match(verifyState, /verification evidence is older than 30 minutes/)
  assert.match(verifyState, /workspace diff changed after the last successful verification evidence/)
  assert.match(verifyState, /latest verification evidence only covers subagent fast checks/)

  const reviewState = readText(join(REPO_ROOT, 'scripts', 'review-state.mjs'))
  assert.match(reviewState, /REVIEW_EVIDENCE_FILE_NAME/)
  assert.match(reviewState, /\.ralph-review\.json/)
  assert.match(reviewState, /VALID_REVIEW_OUTCOMES/)
  assert.match(reviewState, /missing successful review evidence for review-first closeout/)
  assert.match(reviewState, /latest review evidence still records blocking findings/)
  assert.match(reviewState, /review evidence is older than 30 minutes/)
  assert.match(reviewState, /workspace diff changed after the last successful review evidence/)

  const closeoutState = readText(join(REPO_ROOT, 'scripts', 'closeout-state.mjs'))
  assert.match(closeoutState, /CLOSEOUT_EVIDENCE_FILE_NAME/)
  assert.match(closeoutState, /\.ralph-closeout\.json/)
  assert.match(closeoutState, /requirementsCoverage/)
  assert.match(closeoutState, /deliveryChecklist/)
  assert.match(closeoutState, /PASS', 'BLOCKED/)
  assert.match(closeoutState, /missing closeout evidence for requirements coverage and delivery checklist/)
  assert.match(closeoutState, /workspace diff changed after the last successful closeout evidence/)

  const advisorState = readText(join(REPO_ROOT, 'scripts', 'advisor-state.mjs'))
  assert.match(advisorState, /ADVISOR_EVIDENCE_FILE_NAME/)
  assert.match(advisorState, /\.ralph-advisor\.json/)
  assert.match(advisorState, /missing advisor evidence required by the active contract/)
  assert.match(advisorState, /latest advisor evidence still records blocking findings/)

  const visualState = readText(join(REPO_ROOT, 'scripts', 'visual-state.mjs'))
  assert.match(visualState, /VISUAL_EVIDENCE_FILE_NAME/)
  assert.match(visualState, /\.ralph-visual\.json/)
  assert.match(visualState, /missing visual validation evidence required by the active UI contract/)
  assert.match(visualState, /latest visual validation evidence still records blocking findings/)
  assert.match(visualState, /does not cover requested screens/)

  const planContractState = readText(join(REPO_ROOT, 'scripts', 'plan-contract.mjs'))
  assert.match(planContractState, /PLAN_CONTRACT_FILE_NAME/)
  assert.match(planContractState, /contract\.json/)
  assert.match(planContractState, /verifyMode/)
  assert.match(planContractState, /testerFocus/)
  assert.match(planContractState, /reviewerFocus/)
  assert.match(planContractState, /ui\.styleAdvisor/)
  assert.match(planContractState, /ui\.visualValidation/)
  assert.match(planContractState, /advisor\.reason/)
  assert.match(planContractState, /advisor\.preferredSources/)

  const capabilityRegistry = readText(join(REPO_ROOT, 'scripts', 'capability-registry.mjs'))
  assert.match(capabilityRegistry, /plan-contract/)
  assert.match(capabilityRegistry, /advisor-artifact/)
  assert.match(capabilityRegistry, /review-evaluator/)
  assert.match(capabilityRegistry, /design-contract/)
  assert.match(capabilityRegistry, /visual-evaluator/)

  const workflowPlanFiles = readText(join(REPO_ROOT, 'scripts', 'workflow-plan-files.mjs'))
  assert.match(workflowPlanFiles, /still contains template placeholders/)

  const workflowCore = readText(join(REPO_ROOT, 'scripts', 'workflow-core.mjs'))
  assert.match(workflowCore, /未记录活跃方案路径/)
  assert.match(workflowCore, /缺少“主线目标”/)
  assert.match(workflowCore, /缺少“下一步”/)
  assert.match(workflowCore, /方案契约已明确验证主路径/)
  assert.match(workflowCore, /方案契约已明确要求审查优先/)
  assert.match(workflowCore, /STATE\.md 提醒/)
  assert.match(workflowCore, /STATE\.md 只用于找回上次停在哪/)
  assert.match(workflowCore, /验证分流：当前更适合审查优先/)
  assert.match(workflowCore, /验证分流：当前更适合测试优先/)
  assert.match(workflowCore, /UI 约束提示：如本次属于视觉\/交互链路/)
  assert.match(workflowCore, /prd\/03-ui-design\.md/)
  assert.match(workflowCore, /\.helloagents\/\.ralph-visual\.json/)

  const workflowState = readText(join(REPO_ROOT, 'scripts', 'workflow-state.mjs'))
  assert.match(workflowState, /getWorkflowRecommendation/)
  assert.match(workflowState, /当前建议下一命令：~\$\{recommendation\.nextCommand\}/)
  assert.match(workflowState, /当前建议主路径：\$\{recommendation\.nextPath\}/)
  assert.match(workflowState, /当前建议下一阶段：CONSOLIDATE/)
  assert.match(workflowState, /当前更推荐的下一阶段其实是 CONSOLIDATE/)
  assert.match(workflowState, /只有在用户明确提出新增实现范围时，才继续 ~build/)
  assert.match(workflowState, /即使执行 ~verify，也不能越过当前工作流边界/)

  const workflowRecommendation = readText(join(REPO_ROOT, 'scripts', 'workflow-recommendation.mjs'))
  assert.match(workflowRecommendation, /~verify -> CONSOLIDATE/)
  assert.match(workflowRecommendation, /\.helloagents\/\.ralph-advisor\.json/)
  assert.match(workflowRecommendation, /\.helloagents\/\.ralph-visual\.json/)
  assert.match(workflowRecommendation, /\.helloagents\/\.ralph-closeout\.json/)
  assert.match(workflowRecommendation, /编排提示：检测到可并行的开放任务/)
  assert.match(workflowRecommendation, /reviewer \/ hello-review 范围审查/)
  assert.match(workflowRecommendation, /hello-subagent/)
  assert.match(workflowRecommendation, /缺少“涉及文件”“完成标准”或“验证方式”/)
  assert.match(workflowRecommendation, /补齐 `contract\.json`/)
  assert.match(workflowRecommendation, /交付把关：进入 CONSOLIDATE 前，必须先完成 reviewer \/ hello-review/)
  assert.match(workflowRecommendation, /交付把关：当前还不能进入 CONSOLIDATE；先补齐 tasks\.md/)
  assert.match(workflowRecommendation, /交付把关：当前还不能报告完成；先回到 ~build/)
  assert.match(workflowRecommendation, /交付把关：审查与验证证据已满足；先写 `\.helloagents\/\.ralph-closeout\.json`/)
  assert.match(workflowRecommendation, /交付把关：当前已具备收尾证据/)
  assert.match(workflowRecommendation, /留下最新验证证据/)
})

test('workflow templates and bootstrap stay aligned with runtime artifacts', () => {
  const designTemplate = readText(join(REPO_ROOT, 'templates', 'DESIGN.md'))
  for (const section of ['产品表面', '组件与模式', '状态覆盖', '无障碍要求', '禁止事项', '实现备注']) {
    assert.match(designTemplate, new RegExp(`## ${section}`))
  }

  const planTemplate = readText(join(REPO_ROOT, 'templates', 'plans', 'plan.md'))
  assert.match(planTemplate, /## 完成定义/)
  assert.match(planTemplate, /验证主路径（test-first \/ review-first）/)
  assert.match(planTemplate, /reviewer \/ tester 关注边界/)

  const tasksTemplate = readText(join(REPO_ROOT, 'templates', 'plans', 'tasks.md'))
  assert.match(tasksTemplate, /完成标准：/)
  assert.match(tasksTemplate, /验证方式：/)

  const contractTemplate = readText(join(REPO_ROOT, 'templates', 'plans', 'contract.json'))
  assert.match(contractTemplate, /"verifyMode": "\{test-first \| review-first\}"/)
  assert.match(contractTemplate, /"reviewerFocus"/)
  assert.match(contractTemplate, /"testerFocus"/)
  assert.match(contractTemplate, /"advisor"/)
  assert.match(contractTemplate, /"styleAdvisor"/)
  assert.match(contractTemplate, /"visualValidation"/)
  assert.match(contractTemplate, /"preferredSources"/)

  const stateTemplate = readText(join(REPO_ROOT, 'templates', 'STATE.md'))
  assert.match(stateTemplate, /# 恢复快照/)
  assert.match(stateTemplate, /## 主线目标/)

  for (const file of ['bootstrap.md', 'bootstrap-lite.md']) {
    const content = readText(join(REPO_ROOT, file))
    assert.match(content, /Delivery Tier/)
    assert.match(content, /`T0`/)
    assert.match(content, /`T3`/)
    assert.match(content, /`~do` 是 `~build` 的兼容别名/)
    assert.match(content, /plan\.md/)
    assert.match(content, /contract\.json/)
    assert.match(content, /\.ralph-verify\.json/)
    assert.match(content, /\.ralph-review\.json/)
    assert.match(content, /\.ralph-closeout\.json/)
    assert.match(content, /### UI 质量基线/)
    assert.match(content, /记忆点/)
    assert.match(content, /最小设计系统/)
    assert.match(content, /加载、空、错误、成功/)
  }

  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /`~idea` 在输出比较与推荐后结束，不进入实现，也不创建 `\.helloagents\/`、`STATE\.md` 或方案包/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /默认按上文“统一执行流程 \/ ROUTE \/ TIER”选路；除显式 `~command` 外，不另起独立路由规则/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /## 完成约束/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /状态图标与收尾内容必须一致/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /未进入 VERIFY \/ CONSOLIDATE 的路径/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /主线判断依据优先级/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /项目级恢复快照/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /\.ralph-advisor\.json/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /UI 质量基线/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /默认紫白渐变/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /不创建：`~help`、`~idea`/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /### 质量下限（全阶段生效，按项目类型适用）/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /使用目标平台当前稳定、主流、可维护的框架、API 与工程模式/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /适用于标准模式、标准模式\+已激活项目与全局模式/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /默认紫白渐变/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /## 完成约束/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /状态图标与收尾内容必须一致/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /未激活项目且未进入方案包 \/ `contract\.json` \/ 证据链路时/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /主线判断依据优先级/)

  const repoAgents = readText(join(REPO_ROOT, 'AGENTS.md'))
  const bootstrapFull = readText(join(REPO_ROOT, 'bootstrap.md'))
  assert.equal(repoAgents, bootstrapFull)

  const fullstackSkill = readText(join(REPO_ROOT, 'skills', 'commands', 'fullstack', 'SKILL.md'))
  assert.match(fullstackSkill, /functions\/fullstack\.md/)
  assert.match(fullstackSkill, /services\/fullstack\.md/)
  assert.match(fullstackSkill, /~fs/)

  const fullstackFunction = readText(join(REPO_ROOT, 'functions', 'fullstack.md'))
  assert.match(fullstackFunction, /fullstack\/docs\/tasks\.md/)
  assert.match(fullstackFunction, /fullstack\/docs\/agents\.md/)
  assert.match(fullstackFunction, /fullstack\/docs\/upstream\.md/)
  assert.match(fullstackFunction, /artifact_status\.missing/)

  const fullstackService = readText(join(REPO_ROOT, 'services', 'fullstack.md'))
  assert.match(fullstackService, /artifact_status/)
  assert.match(fullstackService, /technical_solution/)

  const fullstackTasksTemplate = readText(join(REPO_ROOT, 'templates', 'fullstack_tasks.md'))
  assert.match(fullstackTasksTemplate, /完成标准/)
  assert.match(fullstackTasksTemplate, /验证方式/)

  const fullstackAgentsTemplate = readText(join(REPO_ROOT, 'templates', 'fullstack_agents.md'))
  assert.match(fullstackAgentsTemplate, /角色边界/)
  assert.match(fullstackAgentsTemplate, /orchestrator/)

  const fullstackUpstreamTemplate = readText(join(REPO_ROOT, 'templates', 'fullstack_upstream.md'))
  assert.match(fullstackUpstreamTemplate, /依赖总览/)
  assert.match(fullstackUpstreamTemplate, /阻塞项/)

  const helpSkill = readText(join(REPO_ROOT, 'skills', 'commands', 'help', 'SKILL.md'))
  assert.match(helpSkill, /~fullstack/)
  assert.match(helpSkill, /`~fs` → 等同 `~fullstack`/)
})
