import test from 'node:test'
import assert from 'node:assert/strict'
import { join } from 'node:path'

import { REPO_ROOT, readText } from './helpers/test-env.mjs'

test('workflow runtime contract keeps route and state scripts aligned', () => {
  const notifyContext = readText(join(REPO_ROOT, 'scripts', 'notify-context.mjs'))
  assert.match(notifyContext, /请根据用户请求的真实意图选路/)
  assert.match(notifyContext, /不依赖关键词表/)
  assert.match(notifyContext, /只读探索/)
  assert.match(notifyContext, /默认先走 ~plan \/ ~prd/)
  assert.match(notifyContext, /当前活跃 plan \/ PRD/)
  assert.match(notifyContext, /describeProjectStoreFile/)
  assert.match(notifyContext, /项目状态：/)
  assert.match(notifyContext, /当前按需能力|buildCapabilityHint|capabilityHint/)
  assert.match(notifyContext, /buildProjectStorageBlock/)
  assert.match(notifyContext, /先看当前用户消息；如果仍是同一任务/)
  assert.match(notifyContext, /状态文件/)
  assert.match(notifyContext, /turnStateCommand/)
  assert.match(notifyContext, /helloagents-turn-state write --kind complete --role main/)

  const packageJson = readText(join(REPO_ROOT, 'package.json'))
  assert.match(packageJson, /"helloagents-turn-state": "scripts\/turn-state-cli\.mjs"/)
  assert.match(readText(join(REPO_ROOT, 'scripts', 'turn-state-cli.mjs')), /turn-state\.mjs/)

  const turnState = readText(join(REPO_ROOT, 'scripts', 'turn-state.mjs'))
  assert.match(turnState, /VALID_KINDS/)
  assert.match(turnState, /VALID_REASON_CATEGORIES/)
  assert.match(turnState, /HELP_TEXT/)
  assert.match(turnState, /reason-category/)
  assert.match(turnState, /turn_state_written/)
  assert.match(turnState, /kind: normalized\.kind/)
  assert.match(turnState, /role: normalized\.role/)
  assert.match(turnState, /reasonCategory: normalized\.reasonCategory/)
  assert.match(turnState, /waiting\/blocked requires reasonCategory and reason/)

  const projectStorage = readText(join(REPO_ROOT, 'scripts', 'project-storage.mjs'))
  assert.match(projectStorage, /project_store_mode/)
  assert.match(projectStorage, /repo-shared/)
  assert.match(projectStorage, /当前项目存储/)
  assert.match(projectStorage, /knowledge_base_dir/)
  assert.match(projectStorage, /artifacts_dir/)

  const guard = readText(join(REPO_ROOT, 'scripts', 'guard.mjs'))
  assert.match(guard, /高风险操作提醒/)
  assert.match(guard, /当前工作流尚未进入 VERIFY \/ CONSOLIDATE/)
  assert.match(guard, /高风险 schema 变更前仍需先完成 ~plan/)
  assert.match(guard, /buildStateSyncHint/)
  assert.match(guard, /buildIdeaBoundaryReason/)
  assert.match(guard, /当前路由：~idea 是只读探索/)
  assert.match(guard, /守卫脚本执行异常，已阻止本次操作以避免静默放行/)

  const guardRules = readText(join(REPO_ROOT, 'scripts', 'guard-rules.mjs'))
  assert.match(guardRules, /HIGH_RISK_COMMAND_PATTERNS/)
  assert.match(guardRules, /IDEA_SIDE_EFFECT_COMMAND_PATTERNS/)
  assert.match(guardRules, /包发布命令/)

  const notifyRoute = readText(join(REPO_ROOT, 'scripts', 'notify-route.mjs'))
  assert.match(notifyRoute, /缺少要展示的配置项/)
  assert.match(notifyRoute, /才读取一次 ~\/\.helloagents\/helloagents\.json/)
  assert.doesNotMatch(notifyRoute, /pending_action_prompted/)
  assert.doesNotMatch(notifyRoute, /pending-action-state/)

  const notify = readText(join(REPO_ROOT, 'scripts', 'notify.mjs'))
  assert.match(notify, /readTurnState/)
  assert.match(notify, /clearTurnState/)
  assert.match(notify, /runTurnStopGate/)
  assert.match(notify, /turnState\.kind === 'complete'/)
  assert.match(notify, /function notifyByLevel/)
  assert.match(notify, /notifyByLevel\('confirm'/)
  assert.match(notify, /notifyByLevel\('warning'/)
  assert.doesNotMatch(notify, /playSound\('warning'\)/)
  assert.doesNotMatch(notify, /desktopNotify\('warning'/)

  const cliMessages = readText(join(REPO_ROOT, 'scripts', 'cli-messages.mjs'))
  assert.match(cliMessages, /已运行会话不会自动重载注入规则/)

  const notifyUi = readText(join(REPO_ROOT, 'scripts', 'notify-ui.mjs'))
  assert.doesNotMatch(notifyUi, /spawnSync/)
  assert.match(notifyUi, /detached: true/)

  const cliCodex = readText(join(REPO_ROOT, 'scripts', 'cli-codex.mjs'))
  assert.match(cliCodex, /cleanupCodexGlobalResidueForStandby/)
  const residueCleanup = cliCodex.slice(
    cliCodex.indexOf('export function cleanupCodexGlobalResidueForStandby'),
    cliCodex.indexOf('export function uninstallCodexStandby'),
  )
  assert.doesNotMatch(residueCleanup, /removeMarkedContent\(join\(codexDir, 'AGENTS\.md'\)\)/)

  const cliLifecycleHosts = readText(join(REPO_ROOT, 'scripts', 'cli-lifecycle-hosts.mjs'))
  assert.match(cliLifecycleHosts, /cleanupCodexGlobalResidueForStandby/)
  assert.doesNotMatch(cliLifecycleHosts, /function installStandby[\s\S]*uninstallCodexGlobal\(runtime\.home\)[\s\S]*function installGlobal/)

  const deliveryGate = readText(join(REPO_ROOT, 'scripts', 'delivery-gate.mjs'))
  const deliveryGateMessages = readText(join(REPO_ROOT, 'scripts', 'delivery-gate-messages.mjs'))
  const deliveryGateContract = `${deliveryGate}\n${deliveryGateMessages}`
  assert.match(deliveryGate, /workflow-aware completion gate/)
  assert.match(deliveryGateContract, /方案包缺少必需文件/)
  assert.match(deliveryGateContract, /模板占位/)
  assert.match(deliveryGateContract, /任务缺少可交付元数据/)
  assert.match(deliveryGateContract, /缺少可信的结构化契约/)
  assert.match(deliveryGateContract, /缺少完成标准/)
  assert.match(deliveryGateContract, /缺少验证方式/)
  assert.match(deliveryGateContract, /缺少最新验证证据/)
  assert.match(deliveryGateContract, /缺少最新 advisor 证据/)
  assert.match(deliveryGateContract, /缺少最新视觉验收证据/)
  assert.match(deliveryGateContract, /缺少最新收尾证据/)
  assert.match(deliveryGateContract, /artifacts\/visual\.json/)
  assert.match(deliveryGateContract, /artifacts\/closeout\.json/)
  assert.match(deliveryGateContract, /处理路径：/)
  assert.doesNotMatch(deliveryGateContract, /建议路径：/)
  assert.match(deliveryGate, /buildDeliveryGateHint/)
  assert.match(deliveryGate, /getVerifyEvidenceStatus/)
  assert.match(deliveryGate, /getReviewEvidenceStatus/)

  const verifyState = readText(join(REPO_ROOT, 'scripts', 'verify-state.mjs'))
  const runtimeArtifacts = readText(join(REPO_ROOT, 'scripts', 'runtime-artifacts.mjs'))
  const runtimeTtl = readText(join(REPO_ROOT, 'scripts', 'runtime-ttl.mjs'))
  assert.match(verifyState, /VERIFY_EVIDENCE_FILE_NAME/)
  assert.match(verifyState, /verify\.json/)
  assert.match(verifyState, /getRuntimeEvidencePath/)
  assert.match(runtimeTtl, /LONG_RUNNING_TTL_HOURS = 720/)
  assert.match(runtimeTtl, /ROUTE_CONTEXT_TTL_MS = LONG_RUNNING_TTL_MS/)
  assert.match(runtimeTtl, /TURN_STATE_TTL_MS = LONG_RUNNING_TTL_MS/)
  assert.match(runtimeTtl, /EVIDENCE_MAX_AGE_MS = LONG_RUNNING_TTL_MS/)
  assert.match(runtimeTtl, /USER_RUNTIME_MAX_AGE_MS = LONG_RUNNING_TTL_MS/)
  assert.match(runtimeArtifacts, /validateEvidenceTimestamp/)
  assert.match(runtimeArtifacts, /超过 \$\{LONG_RUNNING_TTL_HOURS\} 小时/)
  assert.match(runtimeArtifacts, /HEAD:\$\{head/)
  assert.match(runtimeArtifacts, /工作区变更已不同于最近一次/)
  assert.match(verifyState, /最新验证证据只覆盖子代理快速检查/)

  const reviewState = readText(join(REPO_ROOT, 'scripts', 'review-state.mjs'))
  assert.match(reviewState, /REVIEW_EVIDENCE_FILE_NAME/)
  assert.match(reviewState, /review\.json/)
  assert.match(reviewState, /VALID_REVIEW_OUTCOMES/)
  assert.match(reviewState, /缺少 review-first 收尾所需的成功审查证据/)
  assert.match(reviewState, /最新审查证据仍记录阻塞问题/)
  assert.match(reviewState, /validateEvidenceTimestamp/)
  assert.match(reviewState, /成功审查证据/)

  const closeoutState = readText(join(REPO_ROOT, 'scripts', 'closeout-state.mjs'))
  assert.match(closeoutState, /CLOSEOUT_EVIDENCE_FILE_NAME/)
  assert.match(closeoutState, /closeout\.json/)
  assert.match(closeoutState, /requirementsCoverage/)
  assert.match(closeoutState, /deliveryChecklist/)
  assert.match(closeoutState, /PASS', 'BLOCKED/)
  assert.match(closeoutState, /缺少需求覆盖和交付清单的收尾证据/)
  assert.match(closeoutState, /成功收尾证据/)

  const advisorState = readText(join(REPO_ROOT, 'scripts', 'advisor-state.mjs'))
  assert.match(advisorState, /ADVISOR_EVIDENCE_FILE_NAME/)
  assert.match(advisorState, /advisor\.json/)
  assert.match(advisorState, /缺少当前契约要求的 advisor 证据/)
  assert.match(advisorState, /最新 advisor 证据仍记录阻塞问题/)

  const visualState = readText(join(REPO_ROOT, 'scripts', 'visual-state.mjs'))
  assert.match(visualState, /VISUAL_EVIDENCE_FILE_NAME/)
  assert.match(visualState, /visual\.json/)
  assert.match(visualState, /缺少当前 UI 契约要求的视觉验收证据/)
  assert.match(visualState, /最新视觉验收证据仍记录阻塞问题/)
  assert.match(visualState, /未覆盖要求的视口/)

  const planContractState = readText(join(REPO_ROOT, 'scripts', 'plan-contract.mjs'))
  assert.match(planContractState, /PLAN_CONTRACT_FILE_NAME/)
  assert.match(planContractState, /contract\.json/)
  assert.match(planContractState, /verifyMode/)
  assert.match(planContractState, /testerFocus/)
  assert.match(planContractState, /reviewerFocus/)
  assert.match(planContractState, /ui\.styleAdvisor/)
  assert.match(planContractState, /ui\.visualValidation/)
  assert.match(planContractState, /advisor\.reason/)
  assert.match(planContractState, /advisor\.preferredSources/)

  const capabilityRegistry = readText(join(REPO_ROOT, 'scripts', 'capability-registry.mjs'))
  assert.match(capabilityRegistry, /plan-contract/)
  assert.match(capabilityRegistry, /advisor-artifact/)
  assert.match(capabilityRegistry, /review-evaluator/)
  assert.match(capabilityRegistry, /design-contract/)
  assert.match(capabilityRegistry, /visual-evaluator/)

  const workflowPlanFiles = readText(join(REPO_ROOT, 'scripts', 'workflow-plan-files.mjs'))
  assert.match(workflowPlanFiles, /仍包含模板占位内容/)

  const workflowCore = readText(join(REPO_ROOT, 'scripts', 'workflow-core.mjs'))
  assert.match(workflowCore, /未记录活跃方案路径/)
  assert.match(workflowCore, /缺少“主线目标”/)
  assert.match(workflowCore, /缺少“下一步”/)
  assert.match(workflowCore, /方案契约已明确验证主路径/)
  assert.match(workflowCore, /方案契约已明确要求审查优先/)
  assert.match(workflowCore, /状态文件提醒/)
  assert.match(workflowCore, /状态文件只用于找回上次停在哪/)
  assert.match(workflowCore, /验证分流：当前更适合审查优先/)
  assert.match(workflowCore, /验证分流：当前更适合测试优先/)
  assert.match(workflowCore, /UI 约束提示：如本次属于视觉\/交互任务/)
  assert.match(workflowCore, /prd\/03-ui-design\.md/)
  assert.match(workflowCore, /artifacts\/visual\.json/)

  const workflowState = readText(join(REPO_ROOT, 'scripts', 'workflow-state.mjs'))
  assert.match(workflowState, /getWorkflowRecommendation/)
  assert.match(workflowState, /当前应执行 ~\$\{recommendation\.nextCommand\}/)
  assert.match(workflowState, /本次 ~auto 的执行主路径：\$\{recommendation\.nextPath\}/)
  assert.match(workflowState, /当前应直接进入 CONSOLIDATE/)
  assert.match(workflowState, /当前不该继续 ~build/)
  assert.match(workflowState, /用户已显式使用 ~loop/)
  assert.match(workflowState, /只有在用户明确提出新增实现范围时，才继续 ~build/)
  assert.match(workflowState, /即使执行 ~verify，也不能越过当前工作流边界/)

  const workflowRecommendation = readText(join(REPO_ROOT, 'scripts', 'workflow-recommendation.mjs'))
  assert.match(workflowRecommendation, /~verify -> CONSOLIDATE/)
  assert.match(workflowRecommendation, /artifacts\/advisor\.json/)
  assert.match(workflowRecommendation, /artifacts\/visual\.json/)
  assert.match(workflowRecommendation, /artifacts\/closeout\.json/)
  assert.match(workflowRecommendation, /编排提示：检测到可并行的开放任务/)
  assert.match(workflowRecommendation, /reviewer \/ hello-review 范围审查/)
  assert.match(workflowRecommendation, /hello-subagent/)
  assert.match(workflowRecommendation, /缺少“涉及文件”“完成标准”或“验证方式”/)
  assert.match(workflowRecommendation, /补齐 `contract\.json`/)
  assert.match(workflowRecommendation, /交付把关：进入 CONSOLIDATE 前，必须先完成 reviewer \/ hello-review/)
  assert.match(workflowRecommendation, /交付把关：当前还不能进入 CONSOLIDATE；先补齐 tasks\.md/)
  assert.match(workflowRecommendation, /交付把关：当前还不能报告完成；先回到 ~build/)
  assert.match(workflowRecommendation, /交付把关：审查与验证证据已满足；先写当前会话 `artifacts\/closeout\.json`/)
  assert.match(workflowRecommendation, /交付把关：当前已具备收尾证据/)
  assert.match(workflowRecommendation, /留下最新验证证据/)

  const turnStopGate = readText(join(REPO_ROOT, 'scripts', 'turn-stop-gate.mjs'))
  assert.match(turnStopGate, /显式 \$\{commandLabel\} 本轮不应直接停下/)
  assert.match(turnStopGate, /缺少主代理 turn-state/)
  assert.match(turnStopGate, /--kind waiting --role main/)
  assert.match(turnStopGate, /reasonCategory/)
})

test('workflow templates and bootstrap stay aligned with runtime artifacts', () => {
  const designTemplate = readText(join(REPO_ROOT, 'templates', 'DESIGN.md'))
  for (const section of ['产品表面', '组件与模式', '状态覆盖', '无障碍要求', '禁止事项', '实现备注']) {
    assert.match(designTemplate, new RegExp(`## ${section}`))
  }

  const planTemplate = readText(join(REPO_ROOT, 'templates', 'plans', 'plan.md'))
  assert.match(planTemplate, /## 完成定义/)
  assert.match(planTemplate, /## 领域语言/)
  assert.match(planTemplate, /验证主路径（test-first \/ review-first）/)
  assert.match(planTemplate, /reviewer \/ tester 关注边界/)

  const tasksTemplate = readText(join(REPO_ROOT, 'templates', 'plans', 'tasks.md'))
  assert.match(tasksTemplate, /端到端垂直切片/)
  assert.match(tasksTemplate, /AFK/)
  assert.match(tasksTemplate, /HITL/)
  assert.match(tasksTemplate, /预期变更：/)
  assert.match(tasksTemplate, /完成标准：/)
  assert.match(tasksTemplate, /验证方式：/)
  assert.match(tasksTemplate, /Codex \/goal 执行入口/)
  assert.match(tasksTemplate, /不要把完整 PRD 原文直接当作/)

  const contextTemplate = readText(join(REPO_ROOT, 'templates', 'context.md'))
  assert.match(contextTemplate, /## 领域语言/)
  assert.match(contextTemplate, /标准术语/)
  assert.match(contextTemplate, /已消除歧义/)

  const contractTemplate = readText(join(REPO_ROOT, 'templates', 'plans', 'contract.json'))
  assert.match(contractTemplate, /"verifyMode": "\{test-first \| review-first\}"/)
  assert.match(contractTemplate, /"reviewerFocus"/)
  assert.match(contractTemplate, /"testerFocus"/)
  assert.match(contractTemplate, /"advisor"/)
  assert.match(contractTemplate, /"styleAdvisor"/)
  assert.match(contractTemplate, /"visualValidation"/)
  assert.match(contractTemplate, /"preferredSources"/)

  const stateTemplate = readText(join(REPO_ROOT, 'templates', 'STATE.md'))
  assert.match(stateTemplate, /# 恢复快照/)
  assert.match(stateTemplate, /## 主线目标/)

  for (const file of ['bootstrap.md', 'bootstrap-lite.md']) {
    const content = readText(join(REPO_ROOT, file))
    assert.match(content, /## 通用交付规则（强制）/)
    assert.match(content, /## 实现要求（按任务类型适用）/)
    assert.match(content, /## 安全与可靠性/)
    assert.match(content, /## 交互、停顿与收尾/)
    assert.match(content, /## 工作流与完成判定/)
    assert.match(content, /## 项目存储与上下文/)
    assert.match(content, /Delivery Tier/)
    assert.match(content, /`T0`/)
    assert.match(content, /`T3`/)
    assert.match(content, /`~do` 是 `~build` 的兼容别名/)
    assert.match(content, /plan\.md/)
    assert.match(content, /contract\.json/)
    assert.match(content, /artifacts\/verify\.json/)
    assert.match(content, /artifacts\/review\.json/)
    assert.match(content, /artifacts\/closeout\.json/)
    assert.match(content, /### UI 质量基线/)
    assert.match(content, /记忆点/)
    assert.match(content, /最小设计系统/)
    assert.match(content, /加载、空、错误、成功/)
    assert.doesNotMatch(content, /本组规则按任务类型触发；命中后在当前任务涉及的规划、实现、验证阶段持续生效。/)
    assert.doesNotMatch(content, /本组规则按风险场景触发；命中后优先执行，不因任务类型或阶段豁免。/)
    assert.doesNotMatch(content, /本组规则按交互、确认、停顿与收尾场景适用；命中后必须严格执行。/)
    assert.doesNotMatch(content, /本组规则定义任务选路、阶段推进、完成判定与命令边界。/)
    assert.doesNotMatch(content, /本组规则定义项目级存储、运行态文件、上下文恢复与读取优先级。/)
  }

  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /`~idea` 在输出比较与推荐后结束，不进入实现，也不创建 `\.helloagents\/`、状态文件或方案包/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /默认按上文“统一执行流程中的 ROUTE \/ TIER”选路；除显式 `~command` 外，不另起独立路由规则/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /### 完成判定/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /任务状态符号统一使用：`\[ \]` 待办 \| `\[√\]` 完成 \| `\[X\]` 取消 \| `\[-\]` 跳过/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /### 重置/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /覆盖所需配置项/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /输出格式只在缺少 `output_format` 已知值时触发读取/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /主代理必须在本轮最后一条/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /状态图标与收尾内容必须一致/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /helloagents-turn-state write --kind complete --role main/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /普通问候、普通问答、T0 只读分析和一次性解释不调用/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /不要查找、读取或拼接 `turn-state\.mjs` 源码路径/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /稳定命令入口/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /--kind complete/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /reasonCategory/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /blocker\.target/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /不要递归扫描 `\$HOME`、`Downloads`、项目目录或旧版本目录/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /包内脚本优先使用稳定命令入口/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /未进入 VERIFY \/ CONSOLIDATE 的路径/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /### 主线判断依据/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /状态文件（`state_path`）/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /artifacts\/advisor\.json/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /UI 质量基线/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /默认紫白渐变/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /含确认是否执行已给出的方案/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /若正在等待确认，写清待确认动作/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /本地版本检查点/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /需要让运行时识别本轮已完成、等待输入或已阻塞时/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /收尾检查与本地版本检查点/)
  assert.doesNotMatch(readText(join(REPO_ROOT, 'bootstrap.md')), /delivery gate \/ Ralph Loop \/ closeout evidence/)
  assert.doesNotMatch(readText(join(REPO_ROOT, 'bootstrap.md')), /说明：/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /非只读任务完成验证且产生工作区变更时/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /auto_commit_enabled=true/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /auto_commit_enabled=false/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /使用当前回复语言生成简洁 conventional commit message/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /执行 `git commit`/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /显式 `~commit` 不受这个开关影响/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap.md')), /不自动远程 `git push`/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /不创建：`~help`、`~idea`/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /### 工程质量下限（实现任务通用）/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /使用目标平台当前稳定、主流、可维护的框架、API 与工程模式/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /仅在视觉\/交互任务中适用/)
  assert.doesNotMatch(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /适用于标准模式未激活项目、标准模式已激活项目与全局模式/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /默认紫白渐变/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /### 完成判定/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /任务状态符号统一使用：`\[ \]` 待办 \| `\[√\]` 完成 \| `\[X\]` 取消 \| `\[-\]` 跳过/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /### 重置/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /覆盖所需配置项/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /输出格式只在缺少 `output_format` 已知值时触发读取/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /主代理必须在本轮最后一条/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /状态图标与收尾内容必须一致/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /helloagents-turn-state write --kind complete --role main/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /普通问候、普通问答、T0 只读分析和一次性解释不调用/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /不要查找、读取或拼接 `turn-state\.mjs` 源码路径/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /需要让运行时识别本轮已完成、等待输入或已阻塞时/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /稳定命令入口/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /kind=waiting/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /reasonCategory/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /blocker\.target/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /稳定运行根目录 `~\/\.helloagents\/helloagents`/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /只作为兼容别名，不作为优先探测路径/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /未激活项目且未进入方案包 \/ `contract\.json` \/ 证据文件时/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /含确认是否执行已给出的方案/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /若正在等待确认，写清待确认动作/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /本地版本检查点/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /收尾检查与本地版本检查点/)
  assert.doesNotMatch(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /delivery gate \/ Ralph Loop \/ closeout evidence/)
  assert.doesNotMatch(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /说明：/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /非只读任务完成验证且产生工作区变更时/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /auto_commit_enabled=true/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /auto_commit_enabled=false/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /使用当前回复语言生成简洁 conventional commit message/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /执行 `git commit`/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /显式 `~commit` 不受这个开关影响/)
  assert.match(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /### 主线判断依据/)
  assert.doesNotMatch(readText(join(REPO_ROOT, 'bootstrap-lite.md')), /进入统一执行流程\/已激活项目/)

  const repoAgents = readText(join(REPO_ROOT, 'AGENTS.md'))
  const bootstrapFull = readText(join(REPO_ROOT, 'bootstrap.md'))
  assert.equal(repoAgents, bootstrapFull)

  const fullstackSkill = readText(join(REPO_ROOT, 'skills', 'commands', 'fullstack', 'SKILL.md'))
  assert.match(fullstackSkill, /functions\/fullstack\.md/)
  assert.match(fullstackSkill, /services\/fullstack\.md/)
  assert.match(fullstackSkill, /~fs/)

  const fullstackFunction = readText(join(REPO_ROOT, 'functions', 'fullstack.md'))
  assert.match(fullstackFunction, /fullstack\/docs\/tasks\.md/)
  assert.match(fullstackFunction, /fullstack\/docs\/agents\.md/)
  assert.match(fullstackFunction, /fullstack\/docs\/upstream\.md/)
  assert.match(fullstackFunction, /artifact_status\.missing/)

  const fullstackService = readText(join(REPO_ROOT, 'services', 'fullstack.md'))
  assert.match(fullstackService, /artifact_status/)
  assert.match(fullstackService, /technical_solution/)

  const fullstackTasksTemplate = readText(join(REPO_ROOT, 'templates', 'fullstack_tasks.md'))
  assert.match(fullstackTasksTemplate, /完成标准/)
  assert.match(fullstackTasksTemplate, /验证方式/)

  const fullstackAgentsTemplate = readText(join(REPO_ROOT, 'templates', 'fullstack_agents.md'))
  assert.match(fullstackAgentsTemplate, /角色边界/)
  assert.match(fullstackAgentsTemplate, /orchestrator/)

  const fullstackUpstreamTemplate = readText(join(REPO_ROOT, 'templates', 'fullstack_upstream.md'))
  assert.match(fullstackUpstreamTemplate, /依赖总览/)
  assert.match(fullstackUpstreamTemplate, /阻塞项/)

  const helpSkill = readText(join(REPO_ROOT, 'skills', 'commands', 'help', 'SKILL.md'))
  assert.match(helpSkill, /~fullstack/)
  assert.match(helpSkill, /`~fs` → 等同 `~fullstack`/)
})
