export const LONG_RUNNING_TTL_HOURS = 720
export const LONG_RUNNING_TTL_MS = LONG_RUNNING_TTL_HOURS * 60 * 60 * 1000

export const ROUTE_CONTEXT_TTL_MS = LONG_RUNNING_TTL_MS
export const TURN_STATE_TTL_MS = LONG_RUNNING_TTL_MS
export const EVIDENCE_MAX_AGE_MS = LONG_RUNNING_TTL_MS
export const USER_RUNTIME_MAX_AGE_MS = LONG_RUNNING_TTL_MS
